config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'verifications#new'

  resources :verifications, only: [:new, :create, :update]
  resources :domains
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true

  validates :user, presence: true, associated: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :domain

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/verification.rb
class Verification < ActiveRecord::Base
  before_save :set_status

  validates :name, presence: true

  enum status: [:available, :unavailable]

  private

  def set_status
    if !Whois.available?(name) || Domain.where(name: self.name).any?
      self.status = 'unavailable'
    else
      self.status = 'available'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:destroy]
  before_action :authenticate_user!

  def index
    @domains = current_user.domain.all
  end

  def create
    @domain = Domain.new(domain_params)
    @domain.user = current_user
    @domain.save
    redirect_to new_verification_path
  end

  def destroy
    @domain.destroy
    redirect_to domains_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      { name: params.require(:domain_name) }
    end
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :set_verification, only: [:update]

  def new
    @verification = Verification.new
  end

  def create
    @verification = Verification.create(verification_params)

    render :new
  end

  def update
    @verification.update_attributes(verification_params)

    render :new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification
      @verification = Verification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verification_params
      params.require(:verification).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/domains/index.html.haml
- if @domains.any?
  %table
    %thead
      %tr
        %th Name

    %tbody
      - @domains.each do |domain|
        %tr
          %td= domain.name
          %td= link_to 'Destroy', domain, :method => :delete, :data => { :confirm => 'Are you sure?' }
- else
  %h3 There is no reserved domain

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "DomainChecker"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href='/') DomainChecker
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Domains", domains_path
            - unless current_user.present?
              %li= link_to "Sign In", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path
            - else
              %li= link_to "Log Out", destroy_user_session_path, method: 'delete'

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

      %footer

app/views/verifications/_form.html.haml
= form_for @verification do |f|
  - if @verification.errors.any?
    #error_explanation
      %h2= "#{pluralize(@verification.errors.count, "error")} prohibited this verification from being saved:"
      %ul
        - @verification.errors.full_messages.each do |msg|
          %li= msg

  %div#name
    %p
      = f.label :name
      = f.text_field :name

  .actions
    = f.submit 'Verify'

app/views/verifications/new.html.haml
= render 'form'
- if @verification && @verification.name.present?
  - if @verification.available?
    %p
      = "The domain '#{@verification.name}' is available!"
      - if current_user
        = button_to 'Reserve!', domains_path(domain_name: @verification.name)
  - else
    %p
      = "The domain '#{@verification.name}' is unavailable =/"